fix: comment jira integratio

diff --git a/jira-issue-required/action.yml b/jira-issue-required/action.yml
--- a/jira-issue-required/action.yml
+++ b/jira-issue-required/action.yml
@@ -34,23 +34,25 @@ runs:
       shell: bash
       run: echo "POSSIBLE_ISSUE_REFERENCE=${{ github.head_ref }}" >> "$GITHUB_ENV"
 
-    - name: Jira Login
-      uses: atlassian/gajira-login@v3
-      env:
-        JIRA_BASE_URL: ${{ inputs.jira_base_url }}
-        JIRA_USER_EMAIL: ${{ inputs.jira_user_email }}
-        JIRA_API_TOKEN: ${{ inputs.jira_api_token }}
+    # NOTE: uncomment this when fix jira integration
+      
+    #- name: Jira Login
+    #  uses: atlassian/gajira-login@v3
+    #  env:
+    #    JIRA_BASE_URL: ${{ inputs.jira_base_url }}
+    #    JIRA_USER_EMAIL: ${{ inputs.jira_user_email }}
+    #    JIRA_API_TOKEN: ${{ inputs.jira_api_token }}
 
-    - name: Find Issue Key
-      id: find-issue-key
-      uses: atlassian/gajira-find-issue-key@v3
-      with:
-        string: ${{ env.POSSIBLE_ISSUE_REFERENCE }}
-        from: 
-    
-    - name: Fail if not found
-      if: steps.find-issue-key.outputs.issue == '' || steps.find-issue-key.outputs.issue == null
-      shell: bash
-      run: |
-        echo "Issue not found in '${{ env.POSSIBLE_ISSUE_REFERENCE }}'!"
-        exit 1
+    #- name: Find Issue Key
+    #  id: find-issue-key
+    #  uses: atlassian/gajira-find-issue-key@v3
+    #  with:
+    #    string: ${{ env.POSSIBLE_ISSUE_REFERENCE }}
+    #    from: 
+    #
+    #- name: Fail if not found
+    #  if: steps.find-issue-key.outputs.issue == '' || steps.find-issue-key.outputs.issue == null
+    #  shell: bash
+    #  run: |
+    #    echo "Issue not found in '${{ env.POSSIBLE_ISSUE_REFERENCE }}'!"
+    #    exit 1
